### ISSUE TITLE
Where should we put mood trackers?

### ISSUE THREAD

**Issue by adam0white** [woop/awesome-quantified-self#12]
Like [MoodCast](https://2appstudio.com/moodcast/) or [Daylio](http://daylio.webflow.io/)

**Comment by woop** [comment]
Hmmm I was leaning to Mind & Cognition, but I think it would be better to just add a new category underneath Mind & Cognition for Mood.

**Comment by adam0white** [comment]
Created pull request: https://github.com/woop/awesome-quantified-self/pull/13
