### ISSUE TITLE
Splitting up Research and Analysis

### ISSUE THREAD

**Issue by markwk** [woop/awesome-quantified-self#23]
The "Research and Analysis" seems like it might be better split into three sections:

- Blood and Biomarker Testing
- Genetics and DNA Testing
- Microbiome Testing

This will allow us to better share targeted services for each (both for testing and analytics)

@woop how do you feel about this change?

**Comment by woop** [comment]
@markwk As long as we have at least 3 items per sections then I am fine with splitting it. Your sections make sense.
